name: Node.js CI for Hapi Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Debug - Show working directory
        run: pwd
        working-directory: notes-app-back-end

      - name: Debug - List files
        run: ls -la
        working-directory: notes-app-back-end

      - name: Debug - Show package.json
        run: cat package.json
        working-directory: notes-app-back-end

      - name: Install dependencies
        run: npm install
        working-directory: notes-app-back-end

      - name: Add execute permission to jest
        run: chmod +x ./node_modules/.bin/jest
        working-directory: notes-app-back-end

      - name: Run Jest tests
        run: npx jest --coverage
        working-directory: notes-app-back-end

  frontend-tests:
    runs-on: ubuntu-latest
    name: Frontend Tests
    needs: backend-tests # hanya akan jalan jika backend berhasil

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: notes-app-frontend

      - name: Run Frontend Tests
        run: npm test -- --coverage
        working-directory: notes-app-frontend
  deploy-to-vps:
    needs: frontend-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ke VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "🚀 Start deploy..."
            git config --global --add safe.directory /home/arxcbd/Project_FrontEnd_NotesApp_BackEnd_Fundamentals
            cd /home/arxcbd/Project_FrontEnd_NotesApp_BackEnd_Fundamentals/notes-app-frontend || exit 1
            git pull origin main
            docker stop notes-frontend || true
            docker rm notes-frontend || true
            docker build --pull -t notes-app-frontend .
            docker run -d -p 8080:8080 --name notes-frontend notes-app-frontend
            sleep 3
            docker ps -a
            docker logs notes-frontend || true
            echo "✅ Done deploy."
