name: Node.js CI for Hapi Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Debug - Show working directory
        run: pwd
        working-directory: notes-app-back-end

      - name: Debug - List files
        run: ls -la
        working-directory: notes-app-back-end

      - name: Debug - Show package.json
        run: cat package.json
        working-directory: notes-app-back-end

      - name: Install dependencies
        run: npm install
        working-directory: notes-app-back-end

      - name: Add execute permission to jest
        run: chmod +x ./node_modules/.bin/jest
        working-directory: notes-app-back-end

      - name: Run Jest tests
        run: npx jest
        working-directory: notes-app-back-end
  frontend-tests:
    runs-on: ubuntu-latest
    name: Frontend Tests
    needs: backend-tests # hanya akan jalan jika backend berhasil

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: notes-app-frontend

      - name: Run Frontend Tests
        run: npm test -- --watchAll=false
        working-directory: notes-app-frontend
